// Public demo circle seed (Step 30).
//
// Provisions the singleton public circle ("Public Round Circle — Psalms") and
// its seeded AI members, then generates its opening content via REAL Gloo calls
// so the circle reads as a living, in-progress group the moment an Instant
// Access visitor opens it. Idempotent: if the public circle already exists it
// does nothing and returns it, so the seed is safe to run in every environment
// (locally from the dev console; in production once, via the secured admin
// route). Step 31 turns this seed into a daily-refreshed, self-pruning guarantee.
//
// Founding members (both is_bot = true, so no user-targeting sweep touches them):
//   * the RESPONDER bot ("Ada") — a member that also replies live to visitors
//     (src/lib/circle-bot.ts); its id is stored in app_meta.
//   * a static demo persona ("Marcus") — a second real author so the Facilitator
//     digest has the two distinct authors it requires. It never replies live.
// The real "Radoslaw" is NOT seeded (avoids seeding a person's identity into
// prod); he joins manually with his YouVersion account whenever he likes.
//
// Seed content (all real Gloo): the responder posts a member "hello"; both
// members post a day-1 reflection; the responder "completes" day 1 (plan
// progress + conversation starters); then the Facilitator/Summary run produces
// the day-1 digest + lesson summary from the two reflections.

import { eq } from "drizzle-orm";
import { effectiveVersionId } from "@/config/bible-versions";
import { db } from "@/db";
import {
  appMeta,
  circleMembers,
  circles,
  messages,
  userPlanProgress,
  users,
} from "@/db/schema";
import { BOT_RESPONDER_META_KEY } from "@/lib/circle-bot";
import {
  CIRCLE_KIND_PUBLIC,
  loadCirclePlanDay,
  loadPublicCircle,
  PUBLIC_CIRCLE_META_KEY,
} from "@/lib/circles";
import { runCircleDigest } from "@/lib/digest";
import { chatCompletion } from "@/lib/gloo";
import { postConversationStarters } from "@/lib/post-reading";
import { submitReflection } from "@/lib/reflections";
import { fetchPassage } from "@/lib/youversion";

const PUBLIC_CIRCLE_NAME = "Public Round Circle — Psalms";
const PSALMS_PLAN_ID = "psalms-30";
const RESPONDER_NAME = "Ada";
const PERSONA_NAME = "Marcus";
const SEED_LANGUAGE = "en";
const MAX_PASSAGE_CHARS = 4000;

export interface SeedResult {
  /** True when this call provisioned the circle; false when it already existed. */
  seeded: boolean;
  circleId: string;
  detail: string;
}

/** A short warm member "hello" from the responder bot, generated by Gloo. */
async function generateHello(botName: string): Promise<string> {
  const { content } = await chatCompletion({
    agentName: "circle-bot",
    messages: [
      {
        role: "system",
        content:
          `You are ${botName}, a warm member of a small Bible reading circle that is just gathering to read through the Psalms together. ` +
          "Write a short, friendly hello to the circle — two or three sentences — welcoming whoever joins and saying you're glad to read alongside them. " +
          "First person, as a fellow reader (never a host or bot). No markdown, no name prefix, no quotation marks.",
      },
      { role: "user", content: "Introduce yourself and welcome the circle." },
    ],
    maxTokens: 600,
  });
  return content.trim();
}

/** A short honest first-person reflection on the passage, generated by Gloo. */
async function generateReflection(
  personaName: string,
  passageLabel: string,
  passageText: string,
): Promise<string> {
  const { content } = await chatCompletion({
    agentName: "circle-bot",
    messages: [
      {
        role: "system",
        content:
          `You are ${personaName}, a member of a small Bible reading circle. ` +
          "Write a short, honest, personal reflection — two to four sentences — on today's passage: what struck you, a line that stayed with you, or what it stirred. " +
          "First person, plain and real, never a sermon. No markdown, no preamble, no name prefix.",
      },
      {
        role: "user",
        content: `Today's passage (${passageLabel}):\n${passageText}\n\nWrite your reflection.`,
      },
    ],
    maxTokens: 600,
  });
  return content.trim();
}

/**
 * Provision and populate the public demo circle. Idempotent — returns the
 * existing circle untouched if it is already seeded. Real Gloo throughout.
 */
export async function seedPublicDemoCircle(): Promise<SeedResult> {
  const existing = await loadPublicCircle();
  if (existing) {
    return { seeded: false, circleId: existing.id, detail: "already seeded" };
  }

  // --- Structural rows -----------------------------------------------------
  const [bot] = await db
    .insert(users)
    .values({ name: RESPONDER_NAME, language: SEED_LANGUAGE, isBot: true })
    .returning({ id: users.id });
  const [persona] = await db
    .insert(users)
    .values({ name: PERSONA_NAME, language: SEED_LANGUAGE, isBot: true })
    .returning({ id: users.id });

  const [circle] = await db
    .insert(circles)
    .values({
      name: PUBLIC_CIRCLE_NAME,
      planId: PSALMS_PLAN_ID,
      state: "active",
      kind: CIRCLE_KIND_PUBLIC,
      createdBy: bot.id,
    })
    .returning({ id: circles.id });

  await db.insert(circleMembers).values([
    { circleId: circle.id, userId: bot.id },
    { circleId: circle.id, userId: persona.id },
  ]);

  await db
    .insert(appMeta)
    .values({ key: PUBLIC_CIRCLE_META_KEY, value: circle.id })
    .onConflictDoUpdate({ target: appMeta.key, set: { value: circle.id } });
  await db
    .insert(appMeta)
    .values({ key: BOT_RESPONDER_META_KEY, value: bot.id })
    .onConflictDoUpdate({ target: appMeta.key, set: { value: bot.id } });

  // The responder "completes" day 1 of the plan (an in-progress, not finished,
  // group). No progress row for the static persona, so no sweep considers it.
  await db.insert(userPlanProgress).values({
    userId: bot.id,
    planId: PSALMS_PLAN_ID,
    isActive: true,
    completedDays: [1],
  });

  // --- Generated content (real Gloo) ---------------------------------------
  const day = await loadCirclePlanDay(circle.id, 1);
  const reference = day?.reference ?? "PSA.1";
  const label = day?.label ?? "Psalm 1";

  const passage = await fetchPassage(
    reference,
    effectiveVersionId(SEED_LANGUAGE, null),
    { format: "text" },
  );
  const passageText = passage.content.slice(0, MAX_PASSAGE_CHARS);

  // 1) The responder's member "hello".
  const hello = await generateHello(RESPONDER_NAME);
  await db.insert(messages).values({
    circleId: circle.id,
    authorId: bot.id,
    body: hello,
    sourceLanguage: SEED_LANGUAGE,
    kind: "message",
  });

  // 2) A day-1 reflection from each member (two distinct authors → a real
  //    digest). submitReflection runs the Escalation gate first, as everywhere.
  for (const [authorId, name] of [
    [bot.id, RESPONDER_NAME],
    [persona.id, PERSONA_NAME],
  ] as const) {
    const body = await generateReflection(name, label, passageText);
    await submitReflection({
      circleId: circle.id,
      authorId,
      sourceLanguage: SEED_LANGUAGE,
      dayNumber: 1,
      reference,
      label,
      body,
    });
  }

  // 3) The responder finishing day 1 posts the conversation starters.
  await postConversationStarters({
    userId: bot.id,
    circleId: circle.id,
    dayNumber: 1,
    language: SEED_LANGUAGE,
    bibleVersionId: null,
  });

  // 4) The Facilitator + Summary produce the day-1 digest from the reflections.
  const digest = await runCircleDigest(circle.id);

  return {
    seeded: true,
    circleId: circle.id,
    detail: `seeded public circle (digest: ${digest.posted ? "posted" : digest.reason})`,
  };
}
